services:
  - type: web
    name: sistema-avaliacao
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Isso indica que você irá definir esta variável manualmente no painel do Render
      - key: ADMIN_PASSWORD
        sync: false # Defina uma senha forte manualmente no painel do Render 